services:
  elasticsearch:
    image: elasticsearch:9.1.3
    environment:
      ELASTIC_PASSWORD: "test"

  logstash:
    image: logstash:9.1.3
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:9.1.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch