services:
  elasticsearch:
    build: ./elk/elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
    volumes:
      - es_data:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200

  setup:
    build: ./elk/setup
    depends_on:
      - elasticsearch

  logstash:
    build: ./elk/logstash
    depends_on:
      - elasticsearch
    ports:
    - 9600:9600

  kibana:
    build: ./elk/kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}


volumes:
  es_data: