services:
  elasticsearch:
    build: ./elk/elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
    volumes:
      - es_data:/usr/share/elasticsearch/data:Z
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
    ports:
      - 9200:9200
    networks:
      - app


  setup:
    build: ./elk/setup
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
    networks:
      - app


  logstash:
    build: ./elk/logstash
    depends_on:
      - elasticsearch
    ports:
    - 5044:5044
    networks:
      - app
    volumes:
      - ./elk/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - ELASTIC_SEARCH_USERNMAE=${ELASTIC_SEARCH_USERNMAE}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}


  kibana:
    build: ./elk/kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - KIBANA_USERNAME=${KIBANA_USERNAME}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ES_ENCRYPTION_KEY=${ES_ENCRYPTION_KEY}
    networks:
      - app


volumes:
  es_data:

networks:
  app:
    driver: bridge