global:
  scrape_interval: 10s  # Set the default scrape interval to 15 seconds

scrape_configs:
  - job_name: 'app-backend'  # A unique name for your target
    static_configs:
      - targets: ['app-backend:3000']  # Address where Node.js app metrics are exposed
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash-exporter:9198']
  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana-exporter:9684']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - "alerts.yml"

# graphana has to request data from prometheus, that's it
