global:
  scrape_interval: 10s  # Set the default scrape interval

scrape_configs:
  - job_name: 'app-backend'
    static_configs:
      - targets: ['app-backend:3000']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash-exporter:9198']
  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana-exporter:9684']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - "alerts.yml"
