server.host: 0.0.0.0
elasticsearch.hosts: [ http://elasticsearch:9200 ]

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

elasticsearch.username: ${KIBANA_USERNAME}
elasticsearch.password: ${KIBANA_PASSWORD}

xpack.security.encryptionKey: ${ES_ENCRYPTION_KEY}

xpack.fleet.agents.fleet_server.hosts: [ ]
