global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

            
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash-exporter:9198']

rule_files:
  - "alerts.yml"