services:
  elasticsearch:
    build: ./elk/elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
    volumes:
      - es_data:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
    networks:
      - app
    restart: on-failure

  setup:
    build: ./elk/setup
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_SEARCH_USERNMAE=${ELASTIC_SEARCH_USERNMAE}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - app
    restart: on-failure

  logstash:
    build: ./elk/logstash
    depends_on:
      - elasticsearch
    networks:
      - app
    environment:
      - ELASTIC_SEARCH_USERNMAE=${ELASTIC_SEARCH_USERNMAE}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
    restart: on-failure

  kibana:
    build: ./elk/kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - KIBANA_USERNAME=${KIBANA_USERNAME}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ES_ENCRYPTION_KEY=${ES_ENCRYPTION_KEY}
    networks:
      - app
    restart: on-failure




  alertmanager:
    build: ./monitoring/alertmanager
    networks:
      - app
    restart: on-failure
    depends_on:
      - logstash

  prometheus:
    build: ./monitoring/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/data"
      - "--storage.tsdb.retention.time=30d"
    networks:
      - app
    restart: on-failure
    depends_on:
      - alertmanager

  grafana:
    build: ./monitoring/grafana
    ports:
      - "3111:3000"
    networks:
      - app
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: on-failure
    depends_on:
      - prometheus

  elasticsearch-exporter:
    build: ./monitoring/es_exporter
    command:
      - --es.uri=http://${ELASTIC_SEARCH_USERNMAE}:${ELASTIC_SEARCH_PASSWORD}@elasticsearch:9200
      - --es.ssl-skip-verify
    networks:
      - app
    depends_on:
      - elasticsearch
    restart: on-failure

  logstash-exporter:
    build: ./monitoring/logstach_exporter
    networks:
      - app
    depends_on:
      - logstash
    restart: on-failure




  vault-server:
    build: ./vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_SKIP_VERIFY=true
    volumes:
      - ./vault/src/vault.hcl:/etc/vault.d/vault.hcl
      - vault_data:/opt/vault/data
      - shared-data:/me
    networks:
      - app
    restart: on-failure

  nginx:
    build: ./proxy
    ports:
      - "443:443"
    volumes:
      - ./proxy/config/modsecurity.conf:/etc/nginx/modsecurity.conf
      - ./proxy/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
    restart: on-failure

  backend:
    build: app/backend
    working_dir: /usr/src/app
    volumes:
      - ./app/backend/src:/usr/src/app
      - ./app/frontend/src/public:/usr/src/app/public
      - shared-data:/usr/src/app/env
    networks:
      - app
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - REDIRECT_URI=${REDIRECT_URI}
      - PORT=${PORT}
      - HOST=${HOST}
      - WEBSITE_URL=${WEBSITE_URL}
      - SERVER_URL=${SERVER_URL}
    depends_on:
      - logstash
      - vault-server
      - frontend
    restart: on-failure

  frontend:
    build: app/frontend
    working_dir: /usr/src/app
    volumes:
      - ./app/frontend/src:/usr/src/app
    restart: on-failure
    environment: 
      - WS_URL=${WS_URL}

volumes:
  es_data: 
    driver: local
  vault_data: 
    driver: local
  shared-data:
    driver: local

networks:
  app:
    driver: bridge
