services:
  elasticsearch:
    build: ./elk/elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
    volumes:
      - es_data:/usr/share/elasticsearch/data:Z
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
    ports:
      - 9200:9200
    networks:
      - app

  setup:
    build: ./elk/setup
    depends_on:
      - elasticsearch
    environment:
      - ELASTIC_SEARCH_USERNMAE=${ELASTIC_SEARCH_USERNMAE}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - app

  logstash:
    build: ./elk/logstash
    depends_on:
      - elasticsearch
    ports:
    - 5044:5044
    networks:
      - app
    volumes:
      - ./elk/logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - ELASTIC_SEARCH_USERNMAE=${ELASTIC_SEARCH_USERNMAE}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}

  kibana:
    build: ./elk/kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    environment:
      - KIBANA_USERNAME=${KIBANA_USERNAME}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ES_ENCRYPTION_KEY=${ES_ENCRYPTION_KEY}
    networks:
      - app



  prometheus:
    build: ./monitoring/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app


  grafana:
    build: ./monitoring/grafana
    ports:
      - "3000:3000"
    networks:
      - app
    volumes:
      - ./monitoring/grafana/config/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./monitoring/grafana/config/system_metrics.json:/var/lib/grafana/dashboards/system_metrics.json
      - ./monitoring/grafana/config/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  elasticsearch-exporter:
    build: ./monitoring/es_exporter
    ports:
      - "9114:9114"
    command:
      - --es.uri=http://${ELASTIC_SEARCH_USERNMAE}:${ELASTIC_SEARCH_PASSWORD}@elasticsearch:9200
      - "--es.ssl-skip-verify"
    networks:
      - app
    depends_on:
      - elasticsearch

  logstash-exporter:
    build: ./monitoring/logstach_exporter
    ports:
      - "9198:9198"
    volumes:
      - ./monitoring/logstach_exporter/config/config.yml:/app/config.yml
    networks:
      - app
    depends_on:
      - logstash

volumes:
  es_data: 

networks:
  app:
    driver: bridge